#!/usr/bin/env bash

BSPWM_DISPLAYS=$(xrandr | grep " connected" | awk '{print $1}')

workspace_counter=1
for display in $BSPWM_DISPLAYS; do
	workspaces=""
	for integer in {1..10}; do
		workspaces="$workspaces $workspace_counter"
		workspace_counter=$((workspace_counter + 1))
	done
	bspc monitor $display -d $workspaces
done

bspc config border_width 6
bspc config top_padding 30
bspc config window_gap 6
bspc config split_ratio 0.50

bspc config normal_border_color "#000000"
bspc config active_border_color "#808080"
bspc config focused_border_color "#000000"
bspc config presel_feedback_color "#808080"

bspc config single_monocle true
bspc config borderless_monocle true
bspc config gapless_monocle false

bspc config focus_follows_pointer false
bspc config pointer_follows_monitor true
bspc config pointer_follows_focus true
bspc config click_to_focus any
bspc config ignore_ewmh_focus true
#bspc config history_aware_focus true

bspc config external_rules_command ./external_rules

### Screen 1

# Floating
bspc rule -a Dialog state=floating
bspc rule -a lxqt-runner state=floating focus=on follow=on sticky=on center=off border=off
bspc rule -a Zenity state=floating focus=on center=on
bspc rule -a screengrab state=floating focus=on center=on
bspc rule -a mpv state=floating sticky=on border=off

# 1 - Main Utilities
bspc rule -a pcmanfm-qt desktop=^1 #Temporary
bspc rule -a qterminal desktop=^1 #Temporary
bspc rule -a FeatherPad desktop=^1 #Temporary

# 2 - System Management GUI
bspc rule -a pavucontrol-qt desktop=^2 state=tiled
bspc rule -a qps desktop=^2
bspc rule -a lxqt-config desktop=^2
bspc rule -a openrgb desktop=^2

# 3 - Internet Management GUI
bspc rule -a cmst desktop=^3 state=tiled
bspc rule -a CMST desktop=^3 state=tiled
bspc rule -a Transmission-qt desktop=^3
bspc rule -a qBittorrent desktop=^3

# 4 - Interactive Media Management
bspc rule -a q4wine desktop=^4
bspc rule -a q4wine-wrapped desktop=^4
bspc rule -a .q4wine-wrapped desktop=^4
bspc rule -a Steam desktop=^4 state=tiled
bspc rule -a steam desktop=^4 state=tiled
bspc rule -a steamwebhelper desktop=^4 state=tiled

# 5 - Interactive Media
bspc rule -a Wine desktop=^5 state=floating border=off
bspc rule -a "explorer.exe" desktop=^5 state=floating border=off
bspc rule -a "Default - Wine desktop" desktop=^5 state=floating border=off
bspc rule -a "Last Epoch.x86_64" desktop=^5 state=floating border=off

# 6 - Design Software
bspc rule -a Gimp desktop=^6
bspc rule -a godot desktop=^6

# 7 - Coding Software
bspc rule -a kate desktop=^7
bspc rule -a vscodium desktop=^8

### Screen 2

# 11 - Internet Browser
bspc rule -a Firefox desktop=^10 #Temporary
bspc rule -a Nightly desktop=^10 #Temporary
bspc rule -a Navigator desktop=^10 #Temporary

# 12 - Internet Text Communication
bspc rule -a chatterino desktop=^12
bspc rule -a webcord desktop=^12
bspc rule -a discord desktop=^12
bspc rule -a discord-canary desktop=^12
bspc rule -a ripcord desktop=^12

# 13 - Internet Video Communication
bspc rule -a obs desktop=^13
bspc rule -a zoom desktop=^13

sh ./rule-correction.sh
